### PR TITLE
fix: various issues

### PR DESCRIPTION
**Pull request by gzuuus**

### CODE REVIEW

**Comment by plebomoto** [comment]
Stall buttons look off

image

**Comment by plebomoto** [comment]
Not sure if this is within the scope of this PR but the shipping doesn't seem to correspond with the design files:

image

The mobile view seems to off as well.

image

**Comment by gzuuus** [comment]
> Not sure if this is within the scope of this PR but the shipping doesn't seem to correspond with the design files:
> 
> image
> The mobile view seems to off as well.
> 
> image

Yes, its out of the scope of this pr. Tackling the comments now

**Comment by gzuuus** [comment]
codi

> Not sure if this is within the scope of this PR but the shipping doesn't seem to correspond with the design files:
> 
> image
> The mobile view seems to off as well.
> 
> image

I cannot reproduce that glitchy footer, testing in chrome with different responsive templates

**Review by plebomoto — APPROVED** [review]
lg

**Pull request merged**
